environment:
  HIP_VISIBLE_DEVICES: '0'
  VLLM_USE_TRITON_FLASH_ATTN: '0'
vllm_config:
  api_key: abc-123
  model_id: Qwen/Qwen3-8B
  port: 8000
  served_model_name: qwen3-8b
  tp: 8
  trust_remote_code: true
