environment:
  HIP_VISIBLE_DEVICES: '0'
  VLLM_USE_TRITON_FLASH_ATTN: '0'
vllm_config:
  api_key: abc-123
  model_id: meta-llama/Meta-Llama-3-8B-Instruct
  port: 8000
  served_model_name: meta-llama-3-8b-instruct
  tp: 8
  trust_remote_code: true
